services:
  nodejs-server:
    build:
      context: "./nodejs-server"
      dockerfile: "./Dockerfile"
    container_name: nodejs-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs-server/node_modules:/app/node_modules
      - ./nodejs-server:/app
    command: npm run dev

  postgre-sql:
    build:
      context: "./postgre-sql"
      dockerfile: "./Dockerfile"
    container_name: postgre-sql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgre-sql/data:/var/lib/postgresql/data
      - ./postgre-sql/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
