services:
  nodejs-server:
    build:
      context: "./nodejs-server"
      dockerfile: "./Dockerfile"
    container_name: nodejs-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs-server/node_modules:/app/node_modules
      - ./nodejs-server:/app
    command: npm run dev
